//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class approval
    {
        public int approval_id { get; set; }
        public Nullable<int> apply_id { get; set; }
        public int staff_id { get; set; }
        public Nullable<int> result_id { get; set; }
        public Nullable<System.DateTime> approval_date { get; set; }
        public Nullable<int> request_staff_id { get; set; }
        public Nullable<System.DateTime> request_date { get; set; }
        public string approval_path { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> create_staff_id { get; set; }
        public string approval_advice { get; set; }
    }
}
