//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public int attendance_id { get; set; }
        public Nullable<int> staff_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> mobile_id { get; set; }
        public Nullable<System.DateTime> attendance_date { get; set; }
        public int attendance_type { get; set; }
        public int attendance_flag { get; set; }
        public Nullable<System.DateTime> attendance_leave_date { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> create_staff_id { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
        public Nullable<int> delete_staff_id { get; set; }
        public int delete_status { get; set; }
        public Nullable<System.DateTime> attendance_date_offset { get; set; }
        public Nullable<System.DateTime> attendance_leave_date_offset { get; set; }
        public Nullable<int> work_id { get; set; }
        public Nullable<int> in_type_id { get; set; }
        public string in_type_desc { get; set; }
        public Nullable<int> out_type_id { get; set; }
        public string out_type_desc { get; set; }
    }
}
