//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFEntities : DbContext
    {
        public EFEntities()
            : base("name=EFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<android_position> android_position { get; set; }
        public DbSet<approval> approval { get; set; }
        public DbSet<assistant> assistant { get; set; }
        public DbSet<attendance> attendance { get; set; }
        public DbSet<bag> bag { get; set; }
        public DbSet<bth_tag> bth_tag { get; set; }
        public DbSet<company> company { get; set; }
        public DbSet<company_duty> company_duty { get; set; }
        public DbSet<company_line> company_line { get; set; }
        public DbSet<company_range> company_range { get; set; }
        public DbSet<company_station> company_station { get; set; }
        public DbSet<cycle> cycle { get; set; }
        public DbSet<duty> duty { get; set; }
        public DbSet<emergent_maintenance_equipment> emergent_maintenance_equipment { get; set; }
        public DbSet<equipment> equipment { get; set; }
        public DbSet<equipment_circulration> equipment_circulration { get; set; }
        public DbSet<equipment_failure> equipment_failure { get; set; }
        public DbSet<equipment_failure_dealway> equipment_failure_dealway { get; set; }
        public DbSet<equipment_operation> equipment_operation { get; set; }
        public DbSet<equipment_status> equipment_status { get; set; }
        public DbSet<equipment_stock_warn> equipment_stock_warn { get; set; }
        public DbSet<equipment_type> equipment_type { get; set; }
        public DbSet<equipment_used_warn> equipment_used_warn { get; set; }
        public DbSet<exception_log> exception_log { get; set; }
        public DbSet<failure> failure { get; set; }
        public DbSet<failure_dealway> failure_dealway { get; set; }
        public DbSet<install_position> install_position { get; set; }
        public DbSet<level> level { get; set; }
        public DbSet<line> line { get; set; }
        public DbSet<line_station> line_station { get; set; }
        public DbSet<login> login { get; set; }
        public DbSet<login_role> login_role { get; set; }
        public DbSet<lose_warn_type> lose_warn_type { get; set; }
        public DbSet<loser_tag_moniter> loser_tag_moniter { get; set; }
        public DbSet<maintenance_equipment> maintenance_equipment { get; set; }
        public DbSet<maintenance_experience> maintenance_experience { get; set; }
        public DbSet<maintenance_picture> maintenance_picture { get; set; }
        public DbSet<maintenance_plan> maintenance_plan { get; set; }
        public DbSet<maintenance_plan_status> maintenance_plan_status { get; set; }
        public DbSet<maintenance_regulations> maintenance_regulations { get; set; }
        public DbSet<maintenance_result> maintenance_result { get; set; }
        public DbSet<maintenance_staff> maintenance_staff { get; set; }
        public DbSet<maintenance_tools> maintenance_tools { get; set; }
        public DbSet<maintenance_type> maintenance_type { get; set; }
        public DbSet<message> message { get; set; }
        public DbSet<mobile_app_set> mobile_app_set { get; set; }
        public DbSet<mobile_device> mobile_device { get; set; }
        public DbSet<perm> perm { get; set; }
        public DbSet<person_duty> person_duty { get; set; }
        public DbSet<plan_content> plan_content { get; set; }
        public DbSet<pre_code> pre_code { get; set; }
        public DbSet<product_upgrade> product_upgrade { get; set; }
        public DbSet<range_station> range_station { get; set; }
        public DbSet<repair_apply> repair_apply { get; set; }
        public DbSet<repair_detail> repair_detail { get; set; }
        public DbSet<repair_log> repair_log { get; set; }
        public DbSet<role> role { get; set; }
        public DbSet<role_perm> role_perm { get; set; }
        public DbSet<scene_photos> scene_photos { get; set; }
        public DbSet<staff_in_type> staff_in_type { get; set; }
        public DbSet<staff_out_type> staff_out_type { get; set; }
        public DbSet<stat_attendance_rate> stat_attendance_rate { get; set; }
        public DbSet<stat_attendance_rate_staff> stat_attendance_rate_staff { get; set; }
        public DbSet<stat_maintenance_avg_num_person> stat_maintenance_avg_num_person { get; set; }
        public DbSet<stat_maintenance_comparative_person> stat_maintenance_comparative_person { get; set; }
        public DbSet<stat_maintenance_equipment_rate> stat_maintenance_equipment_rate { get; set; }
        public DbSet<stat_style> stat_style { get; set; }
        public DbSet<stat_tool_inout_rate> stat_tool_inout_rate { get; set; }
        public DbSet<stat_tools_rate> stat_tools_rate { get; set; }
        public DbSet<stat_tools_renew_rate> stat_tools_renew_rate { get; set; }
        public DbSet<station> station { get; set; }
        public DbSet<station_type> station_type { get; set; }
        public DbSet<stock> stock { get; set; }
        public DbSet<stock_style> stock_style { get; set; }
        public DbSet<supplier> supplier { get; set; }
        public DbSet<sys_warn> sys_warn { get; set; }
        public DbSet<system_log> system_log { get; set; }
        public DbSet<system_variable_name> system_variable_name { get; set; }
        public DbSet<system_variable_set> system_variable_set { get; set; }
        public DbSet<temporary_staff> temporary_staff { get; set; }
        public DbSet<tool_borrow_type> tool_borrow_type { get; set; }
        public DbSet<tool_epc> tool_epc { get; set; }
        public DbSet<tool_requisit> tool_requisit { get; set; }
        public DbSet<tool_requisit_main> tool_requisit_main { get; set; }
        public DbSet<tool_return_type> tool_return_type { get; set; }
        public DbSet<tools> tools { get; set; }
        public DbSet<tools_in> tools_in { get; set; }
        public DbSet<tools_in_detail> tools_in_detail { get; set; }
        public DbSet<tools_in_material> tools_in_material { get; set; }
        public DbSet<tools_in_type> tools_in_type { get; set; }
        public DbSet<tools_out_type> tools_out_type { get; set; }
        public DbSet<tools_requisit_material> tools_requisit_material { get; set; }
        public DbSet<tools_scan> tools_scan { get; set; }
        public DbSet<tools_style> tools_style { get; set; }
        public DbSet<train> train { get; set; }
        public DbSet<train_style> train_style { get; set; }
        public DbSet<train_video> train_video { get; set; }
        public DbSet<type_experience> type_experience { get; set; }
        public DbSet<v2_maintenance_content> v2_maintenance_content { get; set; }
        public DbSet<v2_maintenance_content_template> v2_maintenance_content_template { get; set; }
        public DbSet<v2_maintenance_item> v2_maintenance_item { get; set; }
        public DbSet<v2_maintenance_item_equipment> v2_maintenance_item_equipment { get; set; }
        public DbSet<v2_maintenance_item_template> v2_maintenance_item_template { get; set; }
        public DbSet<v2_maintenance_record> v2_maintenance_record { get; set; }
        public DbSet<v2_maintenance_record_template> v2_maintenance_record_template { get; set; }
        public DbSet<v2_maintenance_result> v2_maintenance_result { get; set; }
        public DbSet<v2_maintenance_result_template> v2_maintenance_result_template { get; set; }
        public DbSet<v2_maintenance_station_picture> v2_maintenance_station_picture { get; set; }
        public DbSet<v2_month_plan> v2_month_plan { get; set; }
        public DbSet<v2_month_plan_content> v2_month_plan_content { get; set; }
        public DbSet<v2_month_plan_content_detail> v2_month_plan_content_detail { get; set; }
        public DbSet<v2_month_plan_content_detail_staff> v2_month_plan_content_detail_staff { get; set; }
        public DbSet<v2_protection_log> v2_protection_log { get; set; }
        public DbSet<v2_protection_log_detail> v2_protection_log_detail { get; set; }
        public DbSet<v2_shelf> v2_shelf { get; set; }
        public DbSet<v2_work> v2_work { get; set; }
        public DbSet<v2_work_plan> v2_work_plan { get; set; }
        public DbSet<v2_work_subtype> v2_work_subtype { get; set; }
        public DbSet<video_borrow> video_borrow { get; set; }
        public DbSet<warn_deal_set> warn_deal_set { get; set; }
        public DbSet<warn_level> warn_level { get; set; }
        public DbSet<warn_level_relation> warn_level_relation { get; set; }
        public DbSet<warn_message> warn_message { get; set; }
        public DbSet<work_progress> work_progress { get; set; }
        public DbSet<work_range> work_range { get; set; }
        public DbSet<gender> gender { get; set; }
        public DbSet<login_log> login_log { get; set; }
        public DbSet<v2_report_period_type> v2_report_period_type { get; set; }
    }
}
