//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        public int equipment_id { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> equipment_type_id { get; set; }
        public Nullable<int> range_id { get; set; }
        public Nullable<int> line_id { get; set; }
        public Nullable<int> station_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public int cycle_id { get; set; }
        public string equipment_name { get; set; }
        public string equipment_model { get; set; }
        public string device_picture { get; set; }
        public Nullable<System.DateTime> install_date { get; set; }
        public string rfid_code { get; set; }
        public string remark { get; set; }
        public string railway_code { get; set; }
        public Nullable<float> latitude { get; set; }
        public Nullable<float> longitude { get; set; }
        public Nullable<int> equipment_status_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> create_staff_id { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
        public Nullable<int> delete_staff_id { get; set; }
        public int delete_status { get; set; }
        public string rfid_tid { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string ip { get; set; }
        public string port { get; set; }
        public string mac { get; set; }
        public string sn { get; set; }
        public Nullable<int> stock_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public Nullable<int> person_liable_id { get; set; }
        public Nullable<System.DateTime> collar_date { get; set; }
        public Nullable<System.DateTime> buy_date { get; set; }
        public Nullable<System.DateTime> production { get; set; }
        public Nullable<decimal> service_life { get; set; }
        public Nullable<int> is_warn { get; set; }
        public Nullable<System.DateTime> service_end { get; set; }
        public Nullable<int> buy_company { get; set; }
        public Nullable<System.DateTime> circulation_date { get; set; }
        public Nullable<int> update_staff_id { get; set; }
        public Nullable<int> site_flag { get; set; }
        public decimal price { get; set; }
        public Nullable<int> shelf_id { get; set; }
        public string qr_code { get; set; }
        public int is_binding { get; set; }
        public string factory_number { get; set; }
    }
}
