//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment_failure
    {
        public int fault_id { get; set; }
        public Nullable<int> failure_id { get; set; }
        public string rfid_code { get; set; }
        public string fault_description { get; set; }
        public string fault_method { get; set; }
        public Nullable<System.DateTime> fault_date { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> create_staff_id { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
        public Nullable<int> delete_staff_id { get; set; }
        public int delete_status { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<int> update_staff_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> result { get; set; }
        public Nullable<int> response_staff_id { get; set; }
        public Nullable<System.DateTime> response_time { get; set; }
        public Nullable<int> deal_staff_id { get; set; }
        public Nullable<int> apply_staff_id { get; set; }
        public Nullable<System.DateTime> apply_time { get; set; }
    }
}
