//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class loser_tag_moniter
    {
        public int moniter_id { get; set; }
        public int company_id { get; set; }
        public int mobiler_id { get; set; }
        public string tag_jm { get; set; }
        public Nullable<int> tools_id { get; set; }
        public int staff_id { get; set; }
        public System.DateTime begin_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> moniter_state { get; set; }
        public int work_id { get; set; }
        public int moniter_type_id { get; set; }
    }
}
