//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class maintenance_equipment
    {
        public int id { get; set; }
        public Nullable<int> content_id { get; set; }
        public string equipment_code { get; set; }
        public int equipment_id { get; set; }
        public int result_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> is_plan { get; set; }
        public string act_equipment_code { get; set; }
        public Nullable<int> act_equipment_id { get; set; }
    }
}
