//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class maintenance_plan
    {
        public int plan_id { get; set; }
        public Nullable<int> maintenance_type_id { get; set; }
        public Nullable<int> range_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> line_id { get; set; }
        public Nullable<int> station_id { get; set; }
        public System.DateTime begin_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string job_controller { get; set; }
        public string person_in_charge { get; set; }
        public string resident_liaison { get; set; }
        public string liaison_officer { get; set; }
        public string order_nubmer { get; set; }
        public string departure_station { get; set; }
        public string departure_range { get; set; }
        public string maintenance_level { get; set; }
        public string control_model { get; set; }
        public Nullable<System.DateTime> actual_begin_date { get; set; }
        public Nullable<System.DateTime> actual_end_date { get; set; }
        public string job_location { get; set; }
        public string registration_premises { get; set; }
        public string next_time { get; set; }
        public string driving { get; set; }
        public string labour { get; set; }
        public string stop { get; set; }
        public string title { get; set; }
        public string fill_in_person { get; set; }
        public string date_of_filling { get; set; }
        public string opinion { get; set; }
        public string summary { get; set; }
        public int status_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> create_staff_id { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
        public Nullable<int> delete_staff_id { get; set; }
        public int delete_status { get; set; }
        public Nullable<System.DateTime> begin_date_offset { get; set; }
        public Nullable<System.DateTime> end_date_offset { get; set; }
        public Nullable<int> plan_type { get; set; }
    }
}
