//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class maintenance_staff
    {
        public int staff_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> range_id { get; set; }
        public Nullable<int> duty_id { get; set; }
        public Nullable<int> sex { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string card_number { get; set; }
        public string name { get; set; }
        public string picture { get; set; }
        public string tel { get; set; }
        public string job_number { get; set; }
        public string rfid_code { get; set; }
        public Nullable<System.DateTime> check_date { get; set; }
        public Nullable<int> person_type { get; set; }
        public Nullable<System.DateTime> logout_date { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> create_staff_id { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
        public Nullable<int> delete_staff_id { get; set; }
        public int delete_status { get; set; }
        public string rfid_tid { get; set; }
        public int is_system_user { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
    }
}
