//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobile_device
    {
        public int mobile_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string device_name { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public string picture { get; set; }
        public string mobile_model { get; set; }
        public string remark { get; set; }
        public string railway_code { get; set; }
        public string mac { get; set; }
        public Nullable<float> longitude { get; set; }
        public Nullable<float> latitude { get; set; }
        public Nullable<System.DateTime> location_date { get; set; }
        public int equipment_status_id { get; set; }
        public Nullable<int> staff_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> create_staff_id { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
        public Nullable<int> delete_staff_id { get; set; }
        public int delete_status { get; set; }
        public Nullable<int> rang_id { get; set; }
    }
}
