//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobile_app_set
    {
        public int perm_id { get; set; }
        public string perm_name { get; set; }
        public bool perm_state { get; set; }
        public Nullable<bool> is_warn { get; set; }
        public Nullable<int> warn_rank { get; set; }
    }
}
