//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_content
    {
        public int content_id { get; set; }
        public Nullable<int> plan_id { get; set; }
        public string operator_name { get; set; }
        public int operator_id { get; set; }
        public string matual1_man { get; set; }
        public string content { get; set; }
        public string remark { get; set; }
        public Nullable<int> matual1_id { get; set; }
        public string matual2_man { get; set; }
        public Nullable<int> matual2_id { get; set; }
        public int result_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string safe_control { get; set; }
    }
}
