//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_upgrade
    {
        public int id { get; set; }
        public string version_name { get; set; }
        public Nullable<int> version_code { get; set; }
        public string os { get; set; }
        public string filename { get; set; }
        public string type { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> upload_time { get; set; }
        public Nullable<int> upload_user { get; set; }
    }
}
