//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class scene_photos
    {
        public int picture_id { get; set; }
        public int company_id { get; set; }
        public Nullable<int> work_id { get; set; }
        public Nullable<int> requisit_main_id { get; set; }
        public int model_id { get; set; }
        public string picture_path { get; set; }
        public System.DateTime photo_date { get; set; }
        public int mobile_id { get; set; }
        public int staff_id { get; set; }
    }
}
