//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class stat_tool_inout_rate
    {
        public int Id { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public int Order { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int In_Number { get; set; }
        public int Out_Number { get; set; }
        public int CompanyId { get; set; }
        public int GranularityType { get; set; }
        public System.DateTime StatDate { get; set; }
    }
}
