//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class stat_tools_rate
    {
        public int ID { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public string Order { get; set; }
        public string BeginDate { get; set; }
        public string EndDate { get; set; }
        public int RenewNumber { get; set; }
        public int AddNumber { get; set; }
        public int DeleteNumber { get; set; }
        public System.DateTime StartDate { get; set; }
        public int CompanyId { get; set; }
        public int GranularityType { get; set; }
    }
}
