//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class stat_attendance_rate_staff
    {
        public long ID { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public int Order { get; set; }
        public string BeginDate { get; set; }
        public string EndDate { get; set; }
        public int PlanNum { get; set; }
        public int AttendanceNum { get; set; }
        public System.DateTime StatDate { get; set; }
        public int StaffId { get; set; }
        public int GranularityType { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> StationId { get; set; }
    }
}
