//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int stock_id { get; set; }
        public string stock_name { get; set; }
        public int parent_id { get; set; }
        public int company_id { get; set; }
        public System.DateTime create_time { get; set; }
        public int create_staff_id { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<int> update_staff_id { get; set; }
        public Nullable<int> delete_staff_id { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
        public string stock_path { get; set; }
        public int stock_style_id { get; set; }
        public Nullable<int> delete_status { get; set; }
        public string stockcol { get; set; }
    }
}
