//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public int supplier_id { get; set; }
        public string supplier_name { get; set; }
        public string supplier_address { get; set; }
        public string supplier_tel { get; set; }
        public string after_sale_tel { get; set; }
        public string after_sale_name { get; set; }
        public int supplier_status { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> create_staff_id { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
        public Nullable<int> delete_staff_id { get; set; }
        public int delete_status { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> supplier_level_id { get; set; }
        public string supplier_license { get; set; }
        public string supplier_license_no { get; set; }
        public Nullable<int> update_staff_id { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
    }
}
