//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_warn
    {
        public int message_id { get; set; }
        public int company_id { get; set; }
        public string message_info { get; set; }
        public string relevance_id { get; set; }
        public string read_list { get; set; }
        public System.DateTime message_time { get; set; }
    }
}
