//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class temporary_staff
    {
        public int temporary_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> mobile_id { get; set; }
        public string temporary_name { get; set; }
        public int sex { get; set; }
        public string rfid_code { get; set; }
        public string card_number { get; set; }
        public System.DateTime check_date { get; set; }
        public int flag { get; set; }
        public System.DateTime sign_date { get; set; }
        public int sign_type { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> create_staff_id { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
        public Nullable<int> delete_staff_id { get; set; }
        public int delete_status { get; set; }
    }
}
