//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tools_in_material
    {
        public long id { get; set; }
        public long tools_in_id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string unit { get; set; }
        public string desc { get; set; }
        public Nullable<int> in_type { get; set; }
        public string in_type_desc { get; set; }
        public Nullable<int> out_type { get; set; }
        public string out_type_desc { get; set; }
        public Nullable<int> staff_id { get; set; }
        public Nullable<int> material_requisit_id { get; set; }
    }
}
