//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tools_requisit_material
    {
        public long id { get; set; }
        public long requisit_main_id { get; set; }
        public string material_name { get; set; }
        public Nullable<decimal> material_amount { get; set; }
        public string material_unit { get; set; }
        public string material_desc { get; set; }
        public Nullable<int> material_in_type { get; set; }
        public string material_in_type_desc { get; set; }
        public Nullable<int> material_out_type { get; set; }
        public string material_out_type_desc { get; set; }
        public int work_id { get; set; }
        public int staff_id { get; set; }
    }
}
