//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tool_requisit
    {
        public int requisit_id { get; set; }
        public Nullable<int> staff_id { get; set; }
        public Nullable<System.DateTime> borrow_date { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public string epc { get; set; }
        public Nullable<int> tools_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> create_staff_id { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
        public Nullable<int> delete_staff_id { get; set; }
        public int delete_status { get; set; }
        public Nullable<int> work_id { get; set; }
        public int requisit_main_id { get; set; }
        public Nullable<int> return_type { get; set; }
        public string return_type_desc { get; set; }
        public Nullable<int> borrow_type { get; set; }
        public string borrow_type_desc { get; set; }
        public int staff_borrow_state { get; set; }
        public int staff_return_state { get; set; }
    }
}
