//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tools_scan
    {
        public int id { get; set; }
        public Nullable<int> staff_id { get; set; }
        public Nullable<int> mobile_id { get; set; }
        public int in_count { get; set; }
        public Nullable<int> out_cout { get; set; }
        public int station_id { get; set; }
    }
}
