//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tools
    {
        public int tool_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> id { get; set; }
        public string tool_name { get; set; }
        public Nullable<int> tool_no { get; set; }
        public Nullable<int> tool_style_id { get; set; }
        public string tool_rfid { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> create_staff_id { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
        public Nullable<int> delete_staff_id { get; set; }
        public int delete_status { get; set; }
        public string rfid_tid { get; set; }
        public int is_renew { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public short borrow_state { get; set; }
        public Nullable<int> borrow_staff_id { get; set; }
        public Nullable<System.DateTime> borrow_time { get; set; }
        public Nullable<int> bag_id { get; set; }
        public Nullable<int> staff_id { get; set; }
        public Nullable<bool> is_public { get; set; }
        public string factory_number { get; set; }
        public int is_binding { get; set; }
    }
}
