//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tools_in_detail
    {
        public long id { get; set; }
        public long tools_in_id { get; set; }
        public long tools_id { get; set; }
        public string epc { get; set; }
        public Nullable<System.DateTime> in_time { get; set; }
        public Nullable<System.DateTime> out_time { get; set; }
        public int create_staff_id { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<int> delete_staff_id { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
        public Nullable<int> in_type { get; set; }
        public string in_type_desc { get; set; }
        public Nullable<int> out_type { get; set; }
        public string out_type_desc { get; set; }
    }
}
