//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class v2_maintenance_record_template
    {
        public long record_template_id { get; set; }
        public short record_period_type { get; set; }
        public int range_id { get; set; }
        public short report_type { get; set; }
        public string title { get; set; }
        public Nullable<int> result_num { get; set; }
        public string code { get; set; }
        public int create_user { get; set; }
        public System.DateTime create_time { get; set; }
        public bool delete_flag { get; set; }
        public Nullable<int> delete_user { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
    }
}
