//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class v2_month_plan
    {
        public decimal plan_id { get; set; }
        public Nullable<short> plan_type { get; set; }
        public string plan_month { get; set; }
        public Nullable<long> range_id { get; set; }
        public Nullable<int> workshop_manger { get; set; }
        public Nullable<int> workrange_manager { get; set; }
        public Nullable<System.DateTime> plan_date { get; set; }
        public Nullable<int> create_user { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<bool> delete_flag { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
        public Nullable<int> delete_user { get; set; }
    }
}
