//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class v2_month_plan_content
    {
        public decimal content_id { get; set; }
        public long plan_id { get; set; }
        public string location { get; set; }
        public string equipment_name { get; set; }
        public string content { get; set; }
        public string unit { get; set; }
        public Nullable<float> amount { get; set; }
        public Nullable<int> times { get; set; }
        public Nullable<int> result_id { get; set; }
    }
}
