//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class v2_protection_log_detail
    {
        public long log_detail_id { get; set; }
        public long log_id { get; set; }
        public string up { get; set; }
        public string down { get; set; }
        public string notice_time { get; set; }
    }
}
