//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class v2_shelf
    {
        public long shelf_id { get; set; }
        public int station_id { get; set; }
        public string railway_code { get; set; }
        public int manager { get; set; }
        public string rfid { get; set; }
        public string memo { get; set; }
        public int create_user { get; set; }
        public System.DateTime create_time { get; set; }
        public bool delete_flag { get; set; }
        public Nullable<int> delete_user { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
        public string qrcode { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
    }
}
