//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class v2_work
    {
        public int work_id { get; set; }
        public int staff_id { get; set; }
        public string work_name { get; set; }
        public string work_location { get; set; }
        public System.DateTime begin_date { get; set; }
        public System.DateTime end_date { get; set; }
        public int work_type { get; set; }
        public Nullable<int> work_subtype { get; set; }
        public bool work_status { get; set; }
        public bool del_flag { get; set; }
        public Nullable<System.DateTime> del_time { get; set; }
    }
}
