//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class v2_work_subtype
    {
        public int subtype_id { get; set; }
        public string subtype_name { get; set; }
        public System.DateTime create_time { get; set; }
        public int create_user { get; set; }
        public bool del_flag { get; set; }
        public Nullable<System.DateTime> del_time { get; set; }
    }
}
