//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_progress
    {
        public int id { get; set; }
        public int company_id { get; set; }
        public int work_id { get; set; }
        public bool progress_state { get; set; }
        public int create_staff_id { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.DateTime> complete_time { get; set; }
        public Nullable<int> complete_staff_id { get; set; }
        public int model_id { get; set; }
    }
}
